apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flashpaper-dev

resources:
  - ../../base
  - postgres.yaml

patches:
  - path: flashpaper-patch.yaml

images:
  - name: ghcr.io/liskl/flashpaper
    newTag: latest
